syntax = "proto3";
package pingo.v1;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/kamil-koziol/pingo/gen/go/pingo/v1";

message Service {
  int64 id = 1;
  string name = 2;
  string url = 3;
  bool is_active = 4;
  int32 interval_seconds = 5;
  int32 expected_status = 6;
}

message GetServiceRequest {
  int64 id = 1;
}

message ListServicesRequest {
  int32 page_size = 1;
  string page_token = 2;
}

message ListServicesResponse {
  repeated Service services = 1;
  optional string next_page_token = 2;
}

service ServiceService {
  // buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
  rpc GetService(GetServiceRequest) returns (Service) {
    option (google.api.http) = {get: "/v1/services/{id}"};
  }

  rpc ListServices(ListServicesRequest) returns (ListServicesResponse) {
    option (google.api.http) = {get: "/v1/services"};
  }
}

message Ping {
  int64 id = 1;
  int64 service_id = 2;
  int32 status_code = 3;
  int32 latency_ms = 4;
  bool is_up = 5;
  optional string error_message = 6;
  google.protobuf.Timestamp timestamp = 7;
}

message GetPingRequest {
  int64 id = 1;
}

message ListPingsRequest {
  optional int32 page_size = 1;
  optional string page_token = 2;

  optional int64 service_id = 3;
  optional bool is_up = 4;
  
  optional google.protobuf.Timestamp timestamp_after = 5;
  optional google.protobuf.Timestamp timestamp_before = 6;
}

message ListPingsResponse {
  repeated Ping pings = 1;
  optional string next_page_token = 2;
}

service PingService {
  // buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
  rpc GetPing(GetPingRequest) returns (Ping) {
    option (google.api.http) = {get: "/v1/pings/{id}"};
  }

  rpc ListPings(ListPingsRequest) returns (ListPingsResponse) {
    option (google.api.http) = {get: "/v1/pings"};
  }
}
