// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Ping struct {
	ID           int64
	ServiceID    int64
	StatusCode   int64
	LatencyMs    int64
	IsUp         bool
	ErrorMessage sql.NullString
	Timestamp    time.Time
}

type Service struct {
	ID              int64
	Name            string
	Url             string
	IsActive        bool
	IntervalSeconds int64
	ExpectedStatus  int64
}
