// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPing = `-- name: CreatePing :exec
INSERT INTO pings (service_id, status_code, latency_ms, is_up, error_message, timestamp)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePingParams struct {
	ServiceID    int64
	StatusCode   int64
	LatencyMs    int64
	IsUp         bool
	ErrorMessage sql.NullString
	Timestamp    time.Time
}

func (q *Queries) CreatePing(ctx context.Context, arg CreatePingParams) error {
	_, err := q.db.ExecContext(ctx, createPing,
		arg.ServiceID,
		arg.StatusCode,
		arg.LatencyMs,
		arg.IsUp,
		arg.ErrorMessage,
		arg.Timestamp,
	)
	return err
}

const upsertService = `-- name: UpsertService :one
INSERT INTO services (name, url, interval_seconds, expected_status)
VALUES (?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET 
    url=excluded.url,
    interval_seconds=excluded.interval_seconds,
    expected_status=excluded.expected_status
RETURNING id, name, url, is_active, interval_seconds, expected_status
`

type UpsertServiceParams struct {
	Name            string
	Url             string
	IntervalSeconds int64
	ExpectedStatus  int64
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, upsertService,
		arg.Name,
		arg.Url,
		arg.IntervalSeconds,
		arg.ExpectedStatus,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.IntervalSeconds,
		&i.ExpectedStatus,
	)
	return i, err
}
