// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPing = `-- name: CreatePing :exec
INSERT INTO pings (service_id, status_code, expected_status_code, latency_ms, is_up, error_message, timestamp)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePingParams struct {
	ServiceID          int64
	StatusCode         int64
	ExpectedStatusCode int64
	LatencyMs          int64
	IsUp               bool
	ErrorMessage       sql.NullString
	Timestamp          time.Time
}

func (q *Queries) CreatePing(ctx context.Context, arg CreatePingParams) error {
	_, err := q.db.ExecContext(ctx, createPing,
		arg.ServiceID,
		arg.StatusCode,
		arg.ExpectedStatusCode,
		arg.LatencyMs,
		arg.IsUp,
		arg.ErrorMessage,
		arg.Timestamp,
	)
	return err
}

const getPing = `-- name: GetPing :one
SELECT id, service_id, status_code, expected_status_code, latency_ms, is_up, error_message, timestamp FROM pings WHERE id=? LIMIT 1
`

func (q *Queries) GetPing(ctx context.Context, id int64) (Ping, error) {
	row := q.db.QueryRowContext(ctx, getPing, id)
	var i Ping
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.StatusCode,
		&i.ExpectedStatusCode,
		&i.LatencyMs,
		&i.IsUp,
		&i.ErrorMessage,
		&i.Timestamp,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, url, is_active, interval_seconds, expected_status FROM services WHERE id=? LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.IntervalSeconds,
		&i.ExpectedStatus,
	)
	return i, err
}

const getServiceByName = `-- name: GetServiceByName :one
SELECT id, name, url, is_active, interval_seconds, expected_status FROM services WHERE name=? LIMIT 1
`

func (q *Queries) GetServiceByName(ctx context.Context, name string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByName, name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.IntervalSeconds,
		&i.ExpectedStatus,
	)
	return i, err
}

const listActiveServices = `-- name: ListActiveServices :many
SELECT id, name, url, is_active, interval_seconds, expected_status FROM services WHERE is_active=true
`

func (q *Queries) ListActiveServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listActiveServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.IsActive,
			&i.IntervalSeconds,
			&i.ExpectedStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPings = `-- name: ListPings :many
SELECT id, service_id, status_code, expected_status_code, latency_ms, is_up, error_message, timestamp FROM pings
WHERE (?1 IS NULL OR is_up = ?1) AND
(?2 IS NULL OR service_id = ?2) AND
(?3 IS NULL OR timestamp > ?3) AND
(?4 IS NULL OR timestamp < ?4)
`

type ListPingsParams struct {
	IsUp            interface{}
	ServiceID       interface{}
	TimestampAfter  interface{}
	TimestampBefore interface{}
}

func (q *Queries) ListPings(ctx context.Context, arg ListPingsParams) ([]Ping, error) {
	rows, err := q.db.QueryContext(ctx, listPings,
		arg.IsUp,
		arg.ServiceID,
		arg.TimestampAfter,
		arg.TimestampBefore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ping
	for rows.Next() {
		var i Ping
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.StatusCode,
			&i.ExpectedStatusCode,
			&i.LatencyMs,
			&i.IsUp,
			&i.ErrorMessage,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, name, url, is_active, interval_seconds, expected_status FROM services
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.IsActive,
			&i.IntervalSeconds,
			&i.ExpectedStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertService = `-- name: UpsertService :one
INSERT INTO services (name, url, interval_seconds, expected_status)
VALUES (?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET 
    url=excluded.url,
    interval_seconds=excluded.interval_seconds,
    expected_status=excluded.expected_status
RETURNING id, name, url, is_active, interval_seconds, expected_status
`

type UpsertServiceParams struct {
	Name            string
	Url             string
	IntervalSeconds int64
	ExpectedStatus  int64
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, upsertService,
		arg.Name,
		arg.Url,
		arg.IntervalSeconds,
		arg.ExpectedStatus,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.IntervalSeconds,
		&i.ExpectedStatus,
	)
	return i, err
}
