// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreatePing(ctx context.Context, db DBTX, arg CreatePingParams) error
	GetLatestServicePing(ctx context.Context, db DBTX, serviceID int64) (*Ping, error)
	GetPing(ctx context.Context, db DBTX, id int64) (*Ping, error)
	GetServiceByID(ctx context.Context, db DBTX, id int64) (*Service, error)
	GetServiceByName(ctx context.Context, db DBTX, name string) (*Service, error)
	ListLatestPings(ctx context.Context, db DBTX, serviceIds []int64) ([]*ListLatestPingsRow, error)
	ListPings(ctx context.Context, db DBTX, arg ListPingsParams) ([]*Ping, error)
	ListServices(ctx context.Context, db DBTX) ([]*Service, error)
	SetServiceActivity(ctx context.Context, db DBTX, arg SetServiceActivityParams) error
	UpsertService(ctx context.Context, db DBTX, arg UpsertServiceParams) (*Service, error)
}

var _ Querier = (*Queries)(nil)
