// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const upsertService = `-- name: UpsertService :one
INSERT INTO services (name, url, interval_seconds, expected_status)
VALUES (?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET 
    url=excluded.url,
    interval_seconds=excluded.interval_seconds,
    expected_status=excluded.expected_status
RETURNING id, name, url, is_active, interval_seconds, expected_status
`

type UpsertServiceParams struct {
	Name            string
	Url             string
	IntervalSeconds int64
	ExpectedStatus  int64
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, upsertService,
		arg.Name,
		arg.Url,
		arg.IntervalSeconds,
		arg.ExpectedStatus,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.IntervalSeconds,
		&i.ExpectedStatus,
	)
	return i, err
}
