name: Code quality

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Lint
        run: go tool task check
